#Tell travis we need a copy of docker running
sudo: required #SuperUser permissions
language: generic
services:
  - docker

#Build our image using Dockerfile.dev
before_install:
  - docker build -t kushal/docker-react -f Dockerfile.dev .
#Tell Travis how to run our test suite
script:
  - docker run -e CI=true kushal/docker-react npm run test
#Tell Travis how to deploy our code to AWS

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-330992780591"
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
