#Tell travis we need a copy of docker running
sudo: required #SuperUser permissions
language: generic
services:
  - docker

#Build our image using Dockerfile.dev
before_install:
  - docker build -t kushal/docker-react -f Dockerfile.dev .
#Tell Travis how to run our test suite
script:
  - docker run -e CI=true kushal/docker-react npm run test
#Tell Travis how to deploy our code to AWS
